/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                "surface-container-highest": "#22262f",
                "error-dim": "#d7383b",
                "error": "#ff716c",
                "on-error-container": "#ffa8a3",
                "inverse-on-surface": "#52555c",
                "tertiary-fixed": "#a7a9ff",
                "on-secondary-fixed-variant": "#006266",
                "surface-tint": "#61b4fe",
                "on-secondary-container": "#dffdff",
                "inverse-primary": "#00639f",
                "primary-fixed": "#5eb1fc",
                "surface-variant": "#22262f",
                "on-tertiary-fixed": "#060061",
                "on-tertiary": "#090079",
                "surface": "#0b0e14",
                "tertiary-fixed-dim": "#9799ff",
                "on-surface-variant": "#a9abb3",
                "on-primary-container": "#00243f",
                "surface-container-high": "#1c2028",
                "surface-container": "#161a21",
                "on-secondary-fixed": "#004346",
                "tertiary": "#9093ff",
                "outline-variant": "#45484f",
                "on-primary-fixed": "#001222",
                "secondary": "#00f4fe",
                "surface-container-lowest": "#000000",
                "primary": "#61b4fe",
                "on-secondary": "#00575b",
                "secondary-fixed": "#00f4fe",
                "on-tertiary-container": "#ffffff",
                "surface-bright": "#282c36",
                "secondary-container": "#00696e",
                "secondary-dim": "#00e5ee",
                "error-container": "#9f0519",
                "primary-dim": "#4fa3ed",
                "on-primary": "#003152",
                "on-error": "#490006",
                "on-background": "#ecedf6",
                "inverse-surface": "#f9f9ff",
                "outline": "#73757d",
                "on-surface": "#ecedf6",
                "on-primary-fixed-variant": "#00385d",
                "on-tertiary-fixed-variant": "#1600c3",
                "tertiary-container": "#4949fc",
                "surface-dim": "#0b0e14",
                "primary-fixed-dim": "#4fa3ed",
                "tertiary-dim": "#5c5eff",
                "background": "#0b0e14",
                "surface-container-low": "#10131a",
                "secondary-fixed-dim": "#00e5ee",
                "primary-container": "#52a6f0"
            },
            borderRadius: {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            fontFamily: {
                "headline": ["Space Grotesk", "sans-serif"],
                "body": ["Manrope", "sans-serif"],
                "label": ["Manrope", "sans-serif"]
            }
        },
    },
    plugins: [],
}