<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="WolverineFx" Version="5.30.0" />
    <PackageReference Include="WolverineFx.FluentValidation" Version="5.30.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CinemaGo.Domain\CinemaGo.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Bookings\Queries\" />
    <Folder Include="Features\Customers\Commands\" />
    <Folder Include="Features\Customers\ResponseDTOs\" />
    <Folder Include="Features\Customers\Queries\" />
    <Folder Include="Features\Tickets\ResponseDTOs\" />
    <Folder Include="Features\Tickets\Queries\" />
    <Folder Include="Helpers\" />
  </ItemGroup>

</Project>
