<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Alba" Version="8.5.3" />
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.13.0" />
    <PackageReference Include="Testcontainers.Redis" Version="4.13.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ApiTests\" />
    <Folder Include="ApplicationTests\FeatureTests\" />
    <Folder Include="ApplicationTests\MessagingTests\" />
    <Folder Include="InfrastructureTests\PersistenceTests\" />
    <Folder Include="Shared\Fixtures\" />
    <Folder Include="Shared\DataSeeders\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CinemaGo.WebServer\CinemaGo.WebServer.csproj" />
    <ProjectReference Include="..\CinemaGo.UnitTests\CinemaGo.UnitTests.csproj" />
  </ItemGroup>

</Project>